package org.Nicki0.editor.elements;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Object {
	// Für Konstanten etc. 
	// TODO liste vervollständigen
	public static final String[] THINGS_AT_0 = {"Container1","Container2","RocketBiomass1","RocketHeat1","RocketInsects1","RocketOxygen1","RocketPressure1","wreckpilar"};
	public static final long[] INVENTORIES_WITHOUT_CONTAINER = {1,2,109487734,101703877,108035701,109811866,109441691,101767269}; // Player Inventory, Player Addons, Warden Altars (only after completing story, not where they were taken from), Fusion Reactors 
	public static final Map<String, String> translateGIdName = createTranslationMap();
	private static final Map<String, String> createTranslationMap() {
		Map<String, String> result = new HashMap<String, String>();
		result.put("CraftStation2", "Advanced Craft Station");
		result.put("BootsSpeed1", "Agility Boots t1");
		result.put("BootsSpeed2", "Agility Boots t2");
		result.put("BootsSpeed3", "Agility Boots t3");
		result.put("AlgaeGenerator1", "Algae Generator t1");
		result.put("AlgaeGenerator2", "Algae Generator t2");
		result.put("Algae1Seed", "Algae");
		result.put("Algae1Growable", "Algae1Growable");
		result.put("Aluminium", "Aluminium");
		result.put("InsideLamp1", "Area Lamp");
		result.put("RocketHeat1", "Asteroids attraction rocket");
		result.put("WaterCollector1", "Atmospheric Water Collector");
		result.put("Backpack1", "Backpack t1");
		result.put("Backpack2", "Backpack t2");
		result.put("Backpack3", "Backpack t3");
		result.put("Backpack4", "Backpack t4");
		result.put("Backpack5", "Backpack t5");
		result.put("Bacteria1", "Bacteria Sample");
		result.put("Beacon", "Beacon");
		result.put("Vegetable2Seed", "Beans seeds");
		result.put("Vegetable2Growable", "Beans");
		result.put("BedSimple", "Bed");
		result.put("Pod4x", "Big living compartment");
		result.put("Biodome2", "Biodome t2");
		result.put("biodome", "Biodome");
		result.put("Biolab", "Biolab");
		result.put("RocketBiomass1", "Biomass Rocket");
		result.put("Bioplastic1", "Bioplastic nugget");
		result.put("BlueprintT1", "Blueprint microchip");
		result.put("canister", "canister");
		result.put("Chair1", "Chair");
		result.put("Cobalt", "Cobalt");
		result.put("ComAntenna", "Communication Antenna");
		result.put("CraftStation1", "Craft station T2");
		result.put("Desktop1", "Desktop");
		result.put("DisplayCase", "Display case");
		result.put("GeneticManipulator1", "DNA Manipulator");
		result.put("BedDouble", "Double Bed");
		result.put("Drill0", "Drill t1");
		result.put("Drill1", "Drill t2");
		result.put("Drill2", "Drill t3");
		result.put("Drill3", "Drill t4");
		result.put("Vegetable0Seed", "Eggplant seeds");
		result.put("Vegetable0Growable", "Eggplant");
		result.put("EscapePod", "Escape pod");
		result.put("EquipmentIncrease1", "Exoskeleton t1");
		result.put("EquipmentIncrease2", "Exoskeleton t2");
		result.put("RedPowder1", "Explosive powder");
		result.put("FabricBlue", "Fabric");
		result.put("Fertilizer2", "Fertilizer t2");
		result.put("Fertilizer1", "Fertilizer");
		result.put("FlowerPot1", "Flower Pot");
		result.put("SeedSpreader2", "Flower Spreader t2");
		result.put("SeedSpreader1", "Flower Spreader");
		result.put("VegetableGrower2", "Food grower t2");
		result.put("VegetableGrower1", "Food grower");
		result.put("Foundation", "Foundation grid");
		result.put("FusionEnergyCell", "Fusion Energy Cell");
		result.put("FusionGenerator1", "Fusion reactor");
		result.put("GasExtractor1", "Gas Extractor");
		result.put("GoldenContainer", "Golden Crate");
		result.put("GoldenEffigie1", "Golden effigie Rocket");
		result.put("GoldenEffigie2", "Golden effigie Escape Pod");
		result.put("GoldenEffigie3", "Golden effigie Antenna");
		result.put("GoldenEffigieSpawner", "GoldenEffigieSpawner");
		result.put("RocketMap1", "GPS satellite t1");
		result.put("RocketMap2", "GPS satellite t2");
		result.put("RocketMap3", "GPS satellite t3");
		result.put("GrassSpreader1", "Grass spreader");
		result.put("Heater1", "Heater t1");
		result.put("Heater2", "Heater t2");
		result.put("Heater3", "Heater t3");
		result.put("Heater4", "Heater t4");
		result.put("ice", "Ice");
		result.put("Ladder", "Indoor Ladder");
		result.put("Rod-iridium", "Iridium Rod");
		result.put("Iridium", "Iridium");
		result.put("Iron", "Iron");
		result.put("Jetpack1", "Jetpack t1");
		result.put("Jetpack2", "Jetpack t2");
		result.put("Jetpack3", "Jetpack t3");
		result.put("WaterCollector2", "Lake Water Collector");
		result.put("LaunchPlatform", "Launch Platform");
		result.put("podAngle", "Living compartment corner");
		result.put("door", "Living compartment door");
		result.put("FloorGlass", "Living compartment glass");
		result.put("window", "Living compartment window");
		result.put("pod", "Living compartment");
		result.put("Container2", "Locker Storage");
		result.put("Magnesium", "Magnesium");
		result.put("RocketPressure1", "Magnetic field protection rocket");
		result.put("RocketInformations1", "Map information rocket");
		result.put("MethanCapsule1", "Methane cartridge");
		result.put("HudCompass", "Microchip - Compass");
		result.put("MultiBuild", "Microchip - Construction");
		result.put("MultiDeconstruct", "Microchip - Deconstruction");
		result.put("MultiToolMineSpeed1", "Microchip - Mining speed t1");
		result.put("MultiToolMineSpeed2", "Microchip - Mining speed t2");
		result.put("MultiToolMineSpeed3", "Microchip - Mining speed t3");
		result.put("MultiToolMineSpeed4", "Microchip - Mining speed t4");
		result.put("MultiToolLight2", "Microchip – Torch t2");
		result.put("MultiToolLight", "Microchip - Torch");
		result.put("Vegetable3Seed", "Mushroom seeds");
		result.put("Vegetable3Growable", "Mushroom");
		result.put("Mutagen1", "Mutagen");
		result.put("EnergyGenerator6", "Nuclear Fusion generator");
		result.put("EnergyGenerator4", "Nuclear Reactor t1");
		result.put("EnergyGenerator5", "Nuclear Reactor t2");
		result.put("OreExtractor2", "Ore Extractor t2");
		result.put("OreExtractor1", "Ore Extractor");
		result.put("Osmium", "Osmium");
		result.put("OutsideLamp1", "Outside lamp");
		result.put("Stairs", "Outside Stairs");
		result.put("OxygenCapsule1", "Oxygen capsule");
		result.put("OxygenTank1", "Oxygen tank t1");
		result.put("OxygenTank2", "Oxygen tank t2");
		result.put("OxygenTank3", "Oxygen tank t3");
		result.put("OxygenTank4", "Oxygen tank t4");
		result.put("wallplain", "Plain wall");
		result.put("SeedGoldGrowable", "Plant Golden");
		result.put("Seed0Growable", "Plant Lirma");
		result.put("Seed1Growable", "Plant Shanga");
		result.put("Seed2Growable", "Plant Pestera");
		result.put("Seed3Growable", "Plant Nulna");
		result.put("Seed4Growable", "Plant Tuska");
		result.put("Seed5Growable", "Seed5Growable");
		result.put("Seed6Growable", "Seed6Growable");
		result.put("PulsarShard", "Pulsar Quartz Shard");
		result.put("PulsarQuartz", "Pulsar Quartz");
		result.put("PulsarChip", "PulsarChip");
		result.put("RecyclingMachine", "Recycling machine");
		result.put("RocketReactor", "Rocket Engine");
		result.put("ScreenUnlockables", "Screen - Blueprints");
		result.put("ScreenEnergy", "Screen - Energy levels");
		result.put("ScreenMap1", "Screen - Mapping");
		result.put("ScreenRockets", "Screen – Orbital informations");
		result.put("ScreenTerraStage", "Screen - Progress");
		result.put("ScreenTerraformation", "Screen - Terraformation");
		result.put("ScreenMessage", "Screen - Transmissions");
		result.put("Seed0", "Seed Lirma");
		result.put("Seed1", "Seed Shanga (150%)");
		result.put("Seed2", "Seed Pestera (200%)");
		result.put("Seed3", "Seed Nulna (300%)");
		result.put("Seed4", "Seed Tuska (400%)");
		result.put("Seed5", "Plant Orema (450%)");
		result.put("Seed6", "Plant Volnus (500%)");
		result.put("SeedGold", "Golden Seed (600%)");
		result.put("RocketOxygen1", "Seeds spreader rocket");
		result.put("Destructor1", "Shredder machine");
		result.put("Sign", "Sign");
		result.put("Silicon", "Silicon");
		result.put("SofaAngle", "Sofa angle");
		result.put("Sofa", "Sofa");
		result.put("EnergyGenerator2", "Solar panel t1");
		result.put("EnergyGenerator3", "Solar panel t2");
		result.put("astrofood", "Space Food");
		result.put("SpaceMultiplierHeat", "Space heat multiplier");
		result.put("SpaceMultiplierOxygen", "Space oxygen multiplier");
		result.put("SpaceMultiplierPressure", "Space pressure multiplier");
		result.put("SpaceMultiplierBiomass", "SpaceMultiplierBiomass");
		result.put("Vegetable1Seed", "Squash seeds");
		result.put("Vegetable1Growable", "Squash");
		result.put("Container1", "Storage crate");
		result.put("Sulfur", "Sulfur");
		result.put("Rod-alloy", "Super Alloy Rod");
		result.put("Alloy", "Super Alloy");
		result.put("TableSmall", "Table");
		result.put("Teleporter1", "Teleporter");
		result.put("Titanium", "Titanium");
		result.put("TreeRoot", "Tree bark");
		result.put("Tree0Seed", "Tree Seed Iterra (125%)");
		result.put("Tree1Seed", "Tree Seed Linifolia (125%)");
		result.put("Tree2Seed", "Tree Seed Aleatus (125%)");
		result.put("Tree3Seed", "Tree Seed Cernea (150%)");
		result.put("Tree4Seed", "Tree Seed Elegea (175%)");
		result.put("Tree5Seed", "Tree Seed Humelora (250%)");
		result.put("Tree6Seed", "Tree Seed Aemora (400%)");
		result.put("Tree7Seed", "Tree Seed Pleom (350%)");
		result.put("Tree8Seed", "Tree Seed Soleus (125%)");
		result.put("Tree9Seed", "Tree Seed Shreox (450%)");
		result.put("TreeSpreader1", "Tree spreader t2");
		result.put("TreeSpreader2", "Tree spreader t3");
		result.put("TreeSpreader0", "Tree spreader");
		result.put("Tree0Growable", "Tree0Growable");
		result.put("Tree1Growable", "Tree1Growable");
		result.put("Tree2Growable", "Tree2Growable");
		result.put("Tree3Growable", "Tree3Growable");
		result.put("Tree4Growable", "Tree4Growable");
		result.put("Tree5Growable", "Tree5Growable");
		result.put("Tree6Growable", "Tree6Growable");
		result.put("Tree7Growable", "Tree7Growable");
		result.put("Tree8Growable", "Tree8Growable");
		result.put("TreeSpreaderGiant", "TreeSpreaderGiant");
		result.put("Rod-uranium", "Uranium Rod");
		result.put("Uranim", "Uranium");
		result.put("Vegetube1", "Vegetube t1");
		result.put("Vegetube2", "Vegetube t2");
		result.put("VegetubeOutside1", "Vegetube t3");
		result.put("WaterBottle1", "Water bottle");
		result.put("WaterFilter", "Water Filter");
		result.put("EnergyGenerator1", "Wind turbine");
		result.put("wreckpilar", "Wrecks");
		result.put("Zeolite", "Zeolite");
		result.put("astrofood2", "High Quality Food");
		result.put("AutoCrafter1", "Auto-Crafter");
		result.put("Bee1Larvae", "Bee Larva");
		result.put("Beehive1", "Beehive T1");
		result.put("Beehive2", "Beehive T2");
		result.put("Butterfly1Larvae", "Butterfly Azurae Larva (120%)");
		result.put("Butterfly2Larvae", "Butterfly Leani Larva (175%)");
		result.put("Butterfly3Larvae", "Butterfly Fensea Larva (200%)");
		result.put("Butterfly4Larvae", "Butterfly Galaxe Larva (175%)");
		result.put("Butterfly5Larvae", "Butterfly Empalio Larva (120%)");
		result.put("Butterfly6Larvae", "Butterfly Penga Larva (230%)");
		result.put("Butterfly7Larvae", "Butterfly Chevrone Larva (250%)");
		result.put("Butterfly8Larvae", "Butterfly Aemel Larva (300%)");
		result.put("Butterfly9Larvae", "Butterfly Abstreus Larva (175%)");
		result.put("Butterfly10Larvae", "Butterfly Liux Larva (500%)");
		result.put("Butterfly11Larvae", "Butterfly Nere Larva (600%)");
		result.put("Butterfly12Larvae", "Butterfly Lorpen Larva (600%)");
		result.put("Butterfly13Larvae", "Butterfly Fiorente Larva (600%)");
		result.put("Butterfly14Larvae", "Butterfly Alben Larva (700%)");
		result.put("Butterfly15Larvae", "Butterfly Futura Larva (800%)");
		result.put("Butterfly16Larvae", "Butterfly Imeo Larva (1000%)");
		result.put("Butterfly17Larvae", "Butterfly Serena Larva (1200%)");
		result.put("Butterfly18Larvae", "Butterfly Golden Larva (1500%)");
		result.put("ButterflyDisplayer1", "Butterfly Display Box");
		result.put("ButterflyDome1", "Butterfly Dome");
		result.put("ButterflyFarm1", "Butterfly Farm");
		result.put("ButterflyFarm2", "Butterfly Farm T2");
		result.put("Drill4", "Drill T5");
		result.put("Farm1", "Outdoor Farm");
		result.put("Fence", "Fence");
		result.put("GoldenEffige4", "Golden Effige Jet Pack");
		result.put("GoldenEffige5", "Golden Effige Warden's Key");
		result.put("Heater5", "Heater T5");
		result.put("honey", "Honey");
		result.put("Incubator1", "Incubator");
		result.put("LarvaeBase1", "Common Larva");
		result.put("LarvaeBase2", "Uncommon Larva");
		result.put("LarvaeBase3", "Rare Larva");
		result.put("Mutagen2", "Mutagen T2");
		result.put("OreExtractor3", "Ore Extractor T3");
		result.put("RocketInsects1", "Insect Spreader Rocket");
		result.put("Rod-osmium", "Osmium Rod");
		result.put("ScreenBiomass", "Screen Biomass");
		result.put("Silk", "Silk");
		result.put("SilkGenerator", "Silk Generator");
		result.put("SilkWorm", "Silk Worm");
		result.put("SpaceMultiplierInsects", "Space insects multiplier");
		result.put("SpaceMultiplierPlants", "Space plants multiplier");
		result.put("WardenKey", "Warden's Key");
		return result;
	}
	
	public Object() {}
	
	public static List<Item> allItemsOfType(String pGId, List<Item> pItemList) {
		List<Item> listOfType = new ArrayList<>();
		for (int i = 0; i < pItemList.size(); i++) if (pItemList.get(i).getGId().equalsIgnoreCase(pGId)) listOfType.add(pItemList.get(i));
		return listOfType;
	}
}
